@startuml

autoactivate on

actor Administrador

participant "Frontend" as Frontend
participant "API REST" as API
participant "Serviço de Relatórios" as Service
database "PostgreSQL" as DB

Administrador -> Frontend : Solicita relatório
activate Administrador
Frontend -> API : GET /relatorios

API -> Service : gerarRelatorio()

Service -> DB : consultarDados()

alt Dados encontrados

    DB --> Service : dados do sistema

    Service -> Service : gerar relatório

    Service --> API : relatório gerado

    API --> Frontend : relatório

    Frontend --> Administrador : Exibe relatório

else Nenhum dado encontrado

    DB --> Service : lista vazia

    Service --> API : erro

    API --> Frontend : mensagem

    Frontend --> Administrador : Nenhum dado disponível

end

deactivate Administrador
@enduml