@startuml

autoactivate on

actor Organizador

participant "Frontend" as Frontend
participant "API REST" as API
participant "Serviço de Eventos" as Service
database "PostgreSQL" as DB

Organizador -> Frontend : Solicita lista de participantes
activate Organizador
Frontend -> API : GET /eventos/{id}/participantes

API -> Service : consultarParticipantes(idEvento)

Service -> DB : buscarInscricoes(idEvento)

alt Participantes encontrados

    DB --> Service : lista de participantes

    Service --> API : participantes encontrados

    API --> Frontend : lista de participantes

    Frontend --> Organizador : Exibe participantes

else Nenhum participante inscrito

    DB --> Service : lista vazia

    Service --> API : nenhum participante encontrado

    API --> Frontend : lista vazia

    Frontend --> Organizador : Nenhum participante inscrito

end
deactivate Organizador
@enduml